car_dealership/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('cars/', views.cars_page, name='cars'),
    path('car_dy/', views.cars, name='car_dy'),
    path('car_s/', views.car_search, name='search'),
    path('car/<int:cid>', views.car_details, name='details'),
    path('testdrive/<int:cid>', views.testdrive, name="testdrive"),
    path('ordercar/<int:cid>', views.order_car, name='order'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('compare/', views.compare, name='compare'),
    path('searchcar/', views.search, name='searchcar'),
    path('searchA/',views.searchA, name='searchA'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/web/car_details.html
{% extends 'web/base_alt.html' %}
{% load staticfiles %}
{% block title %}{{ car.brand }} {{ car.name }}{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-t rigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h3 class="my-4">{{ car.brand }}</h3>
            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div class="card mt-4">
                    <img class="card-img-top img-fluid" src="{{ car.picture.url }}" alt="">
                    <div class="card-body">
                        <h3 class="card-title">{{ car.name }}</h3>
                        <h4>&#8377; {{ car.price }}</h4>
                        <p class="card-text">{{ car.description }}</p>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="testdriveBtn">
                            Book a test drive
                        </button>
                        &nbsp;&nbsp;&nbsp;
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#order" id="orderBtn">
                            Order now
                        </button>
                    </div>
                </div>
                <!-- /.card -->

                <div class="card card-outline-secondary my-4">
                    <div class="card-header">
                        Specification
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <td>
                                    Car type
                                </td>
                                <td>
                                    {{ car.car_make }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Fuel Type
                                </td>
                                <td>
                                    {{ car.fuel }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Seating capacity
                                </td>
                                <td>
                                    {{ car.seats }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Fuel Tank Capacity (litres)
                                </td>
                                <td>
                                    {{ car.tank_capacity }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Transmission type
                                </td>
                                <td>
                                    {{ car.transmission }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Gears
                                </td>
                                <td>
                                    {{ car.gears }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Engine displacement (cc)
                                </td>
                                <td>
                                    {{ car.engine_displacement }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Maximum power (PS)
                                </td>
                                <td>
                                    {{ car.power }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Dimensions (mm)
                                </td>
                                <td>
                                    {{ car.dimensions }}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col-lg-9 -->
        </div>

    </div>


    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Book a test drive</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <form id="testdriveForm" class="form form-control" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="date-input">
                                Date:
                            </label>
                            <div class="col-sm-10">
                                <input id="date-input" class="datepicker" maxlength="30" name="date" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success" id="regisBtn">Register</button>
                            </div>
                        </div>
                    </form>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button id="testdriveClose" type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>


    <div class="modal fade" id="order">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Order the car?</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <form id="orderForm" class="form form-control" role="form" action="{% url 'web:order' car.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="address">
                                Address:
                            </label>
                            <div class="col-sm-10">
                                <textarea rows="4" cols="50" id="address" name="address"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success" id="clickBtn">Order</button>
                            </div>
                        </div>
                    </form>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button id="orderClose" type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/additional-methods.js' %}" type="text/javascript"></script>

    <script>

        var date = new Date();
        date.setDate(date.getDate()-1);

        $('.datepicker').datepicker({
            format: "dd/mm/yyyy",
            autoclose: true,
            startDate: date
        });


        $("#testdriveForm").submit(function(e) {

            var url = "{% url 'web:testdrive' car.id %}";
            $.ajax({
                   type: "POST",
                   url: url,
                   data: $("#testdriveForm").serialize(),
                   success: function(data)
                   {
                       alert(data);
                   }
                 });
            $("#testdriveClose").trigger("click");
            e.preventDefault();
        });


        $("#orderForm").submit(function(e) {

            var url = "{% url 'web:order' car.id %}";
            $.ajax({
                   type: "POST",
                   url: url,
                   data: $("#orderForm").serialize(),
                   success: function(data)
                   {
                       alert(data);
                   }
                 });
            $("#orderClose").trigger("click");
            e.preventDefault();
        });

    </script>

{% endblock %}

web/templates/web/compare.html
{% extends 'web/base_alt.html' %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block title %}Compare{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-select.min.css' %}" id="theme-stylesheet">
    <script src="{% static 'js/nouislider.min.js' %}"></script>
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" id="searchbar">
                <input class="form-control ml-sm-2" type="text" name="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="submit">Search</button>
            </form>
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block body %}
    <section class="hero hero-page gray-bg padding-small">
        <div class="container">
            <div class="row d-flex">
                <div class="col-lg-9 order-2 order-lg-1">
                    <h1>Compare cars</h1>
                    <p class="lead text-muted">Specs of 2 cars, side by side</p>
                </div>
                <div class="col-lg-3 text-right order-1 order-lg-2">
                    <ul class="breadcrumb justify-content-lg-end">
                        <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">compare</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <main>
        <div class="container">
            <div class="row">
                <!-- Select-->
                <div class="products-grid col-xl-12 col-lg-12" style="text-align: center">
                    <form id="compareForm" class="form form-control" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form form layout='horizontal'%}
                        {% buttons %}
                            <button type="submit" class="btn btn-success" id="compareBtn">Compare</button>
                        {% endbuttons %}
                    </form>
                </div>
            </div>
                <!-- /Select end-->
            <div class="row">
                <!-- Grid -->
                <div class="products-grid col-xl-12 col-lg-12 sidebar-left">
                    <div class="row grid" id="tablezone">
                        <!-- item-->
                    </div>
                </div>
                <!-- / Grid End-->
            </div>
        </div>
    </main>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script>
        $("#compareForm").submit(function(e) {
            var url = "{% url 'web:compare' %}";
            $.ajax({
                type: "POST",
                url: url,
                data: $("#compareForm").serialize(),
                success: function(data) {
                    $('#cmpTable').remove();
                    $('#tablezone').append(data);
                }
            });
            e.preventDefault();
        });
    </script>
{% endblock %}

web/templates/web/dashboard.html
{% extends 'web/base_alt.html' %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#">Welcome, {{ user.last_name }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-t rigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block body %}
    <div class="container">

        <!-- Page Heading -->
        <h3 class="my-4">Test drives
{#            <small>All test drives</small>#}
        </h3>

        <div class="row">
            {% comment %}Loop comes here{% endcomment %}
            {% if tests %}
                {% for test in tests %}
                    <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
                        <div class="card h-100">
                            <a href="{% url 'web:details' test.car.id %}"><img class="card-img-top" src="{{ test.car.picture.url }}" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="{% url 'web:details' test.car.id %}">{{ test.car.brand }} {{ test.car.name }}</a>
                                </h4>
                                <p class="card-text">
                                    Date of test drive: {{ test.time }}<br>
                                    Approved: {% if test.approved %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <!-- /.row -->
    </div>
    <div class="container">

        <!-- Page Heading -->
        <h3 class="my-4">Orders
{#            <small>Secondary Text</small>#}
        </h3>

        <div class="row">
            {% if orders %}
                {% for order in orders %}
                    <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
                        <div class="card h-100">
                            <a href="{% url 'web:details' order.car.id %}"><img class="card-img-top" src="{{ order.car.picture.url }}" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="{% url 'web:details' test.car.id %}">{{ order.car.brand }} {{ order.car.name }}</a>
                                </h4>
                                <p class="card-text">
                                    Amount: &#8377; {{ order.amount }}<br>
                                    Date of order: {{ order.order_time }}<br>
                                    Address: {{ order.address }}<br>
                                    Delivered: {% if order.is_delivered %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <!-- /.row -->
    </div>
{% endblock %}

web/templates/web/search.html
{% extends 'web/base_alt.html' %}
{% load staticfiles %}
{% block title %}Cars{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/nouislider.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
    <script src="{% static 'js/nouislider.min.js' %}"></script>
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <form class="form-inline my-2 my-lg-0" id="searchbar">
                <input class="form-control ml-sm-2" type="text" name="search" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" id="submit">Search</button>
            </form>
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:compare' %}">Compare</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:dashboard' %}">Welcome, {{ user.last_name }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'web:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
{% block body %}
    <section class="hero hero-page gray-bg padding-small">
        <div class="container">
            <div class="row d-flex">
                <div class="col-lg-9 order-2 order-lg-1">
                    <h3>Cars</h3>
                    <p class="lead text-muted">Available cars in the showroom</p>
                </div>
                <div class="col-lg-3 text-right order-1 order-lg-2">
                    <ul class="breadcrumb justify-content-lg-end">
                        <li class="breadcrumb-item"><a href="{% url 'web:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">cars</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
<main>
        <div class="container">
            <div class="row">
 <!-- Grid -->
                <div class="products-grid col-xl-9 col-lg-8 sidebar-left">
                    <div class="row grid">
                        <!-- item-->
                    </div>


                    <br>
                    <nav aria-label="page navigation example" class="d-flex justify-content-center">
                        <ul class="pagination pagination-custom">
                            <li class="page-item" id="prev" onclick="previous()"><a href="#" aria-label="Previous" class="page-link"><span
                                    aria-hidden="true">Prev</span><span class="sr-only">Previous</span></a></li>
                            <li class="page-item" id="next" onclick="next()"><a href="#" aria-label="Next" class="page-link"><span
                                    aria-hidden="true">Next</span><span class="sr-only">Next     </span></a></li>
                        </ul>
                    </nav>
                </div>
                <!-- / Grid End-->
            </div>
        </div>
</main>
{% endblock %}
{% block scripts %}
<script>
 function tryParseJSON (jsonString){
            try {
                var o = JSON.parse(jsonString);
                if (o && typeof o === "object") {
                    return o;
                }
            }
            catch (e) { }
            return false;
        }
    function previous() {
            if (filter === true) {
                if (start === 0) {
                    // There's no previous then..
                }
                else {
                    start = start - 9;
                    end = start + 9;
                    getparams(start, end);
                }
            }
            else if (q === true) {
                if (start === 0) {
                    // There's no previous then..
                }
                else {
                    start = start - 9;
                    end = start + 9;
                    searchb(start, end);
                }
            }
            else {
                if (start === 0) {
                    //There's no previous here
                }
                else {
                    start = start - 9;
                    end = start + 9;
                    getGrid(start, end);
                }
            }
        }


        function next() {
            if (filter === true) {
                start = start + 9;
                end = start + 9;
                getparams(start, end);
            }
            else if (q === true) {
                start = start + 9;
                end = start + 9;
                searchb(start, end);
            }
            else {
                start = start + 9;
                end = start + 9;
                getGrid(start, end);
            }
        }

            function XMLReq(callback) {
            var response = '';
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (this.readyState === 4 && this.status === 200) {
                    response = this.responseText;
                    callback(response);
                }
            };
            return xhttp;
        }

        function getGrid(start, end) {
            // Get checkbox value here.
            // And also the my accounts only checkbox
            var xhttp = XMLReq(fillGrid);
            var query = 'start=' + start + '&end=' + end;
            var local = window.location.origin;
            xhttp.open("GET", local + '/car_dy' + '?' + query, true);
            xhttp.send();
        }

        function fillGrid(data) {
            clear();
            var local = window.location.origin;
            var parsed = tryParseJSON(data);
            if (parsed === false) {
                //It's not JSON. It's something.
            }
            else {

                if (parsed.length === 0) {
                    var markup = '<p id=error>Uh oh! No cars with matching queries found!</p><br>';
                    $('.grid').append(markup);
                }
                else {
                    for (var obj in parsed) {
                        var ob = parsed[obj];
                        var pk = ob['pk'];
                        var fields = ob['fields'];
                        var name = fields['name'];
                        var brand = fields['brand'];
                        var price = fields['price'];
                        var pic = fields['picture'];

                        // Now add the table. :)
                        var markup = '<div class="item col-xl-4 col-md-6">' +
                            '<div class="product is-gray"> ' +
                                '<div class="image d-flex align-items-center justify-content-center">' +
                                    '<img src="'+ local + '/media/' + pic +'" alt="" class="img-fluid">' +
                                    '<div class="hover-overlay d-flex align-items-center justify-content-center">' +
                                        '<div class="CTA d-flex align-items-center justify-content-center">' +
                                            '<a href="' + local + '/car/' + pk +'" class="visit-product active">' +
                                                '<i class="icon-search"></i>' +
                                                'View' +
                                            '</a>' +
                                        '</div>' +
                                    '</div>' +
                                '</div>' +
                                '<div class="title">' +
                                    '<small class="text-muted">' + brand + '</small>' +
                                        '<a href="' + local + '/car/' + pk + '">' +
                                            '<h3 class="h6 text-uppercase no-margin-bottom">' + name + '</h3>' +
                                        '</a>' +
                                        '<span class="price text-muted">&#8377; ' + price + '</span>' +
                                '</div>' +
                            '</div>' +
                            '</div>';

                        $('.grid').append(markup);
                    }
                }
            }
        }

        function searchb(start, end) {
            q = true;
            filter = false;
            var term = $('#searchbar').serialize();
            console.log(term)
            var xhttp = XMLReq(fillGrid);
            var local = window.location.origin;
            var extra = "&start=" + start + "&end=" + end;
            xhttp.open("GET", local + '/car_s' + '?' + term + extra, true);
            xhttp.send();
        }

        function clear () {
            $(".item").remove();
            $("#error").remove();
        }

        getGrid(0,9);

     $("#searchbar").submit(function(e){
            searchb(start, end);
            return false;
        });

    </script>
{% endblock %}

def search(request,pg=1):
    brand = request.GET.get('brand')
    vehicle = request.GET.get('vehicle')
    budget = str(request.GET.get('price'))
    # rbudget = request.GET.get('rbudget')
    rbrand = request.GET.get('rbrand')
    print("Hello ",brand, vehicle, budget ,rbrand)
    # Each page has 9 requests. That is fixed.
    start = (pg - 1) * 9
    end = start + 9

    # # fetch car
     if rbrand=="brand":
         print("*************")
         objs = Car.objects.filter(
             Q(brand__icontains=brand) & Q(body_type__icontains=vehicle)
             )[start:end]
         print("objs::",objs)
     else:
        num = budget.split('-')
        p_min = num[0] + "00000"
        p_max = num[1] + "00000"
        # objs = Car.objects.all()
        objs = Car.objects.filter(
          Q(body_type__icontains=vehicle) & Q(price__range=(p_min,p_max))
        )[start:end]

     context = {
        'objs': objs
    }
    print("context:",context)
    # data = serializers.serialize('json', objs)
    return render(request, 'web/cars.html', context)